# -*- coding: utf-8 -*-
"""KMeans mall customer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17oixEyeha1XBN8nsZfdI_HSRWWyt96Vl
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

df = pd.read_csv("/content/Mall_Customers (1).csv")

df

df.head()

df.info()

df.isnull().sum()

df.duplicated().sum()  #duplicate rows count

plt.scatter(df['Annual Income (k$)'],df['Spending Score (1-100)'])
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.title('Customer Distribution')
plt.show()

X = df[['Annual Income (k$)', 'Spending Score (1-100)']]

sc = StandardScaler()
X_scaled = sc.fit_transform(X)

# Elbow Mathod
wcss = []
for i in range(1,11):
  kmeans = KMeans(n_clusters = i , random_state = 42)
  kmeans.fit(X_scaled)
  wcss.append(kmeans.inertia_)

plt.plot(range(1,11),wcss, marker='o' , color='blue')
plt.xlabel("Number of Clusters")
plt.ylabel('WCSS')
plt.title('Elbow Method')
plt.show()

from sklearn.metrics import silhouette_score

for i in range(2,11):
  kmeans = KMeans(n_clusters = i , random_state=42)
  labels = kmeans.fit_predict(X_scaled)
  score = silhouette_score(X_scaled , labels)
  print(f"K = {i} , Silhoutte Score {score}")

kmeans = KMeans(n_clusters = 5, random_state = 42)
df['Cluster'] = kmeans.fit_predict(X_scaled)

df.head()

plt.scatter(df['Annual Income (k$)'],df['Spending Score (1-100)'],c = df['Cluster'])
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.title('Customer Distribution')
plt.show()